# Generated by Django 4.1.7 on 2023-03-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': 'Relation', 'verbose_name_plural': 'Relations'},
        ),
        migrations.AddIndex(
            model_name='relation',
            index=models.Index(fields=['follower', 'following'], name='relations_followe_efb523_idx'),
        ),
        migrations.AlterModelTable(
            name='relation',
            table='relations',
        ),
    ]
